services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
      args:
        - SERVER_BASE_URL=${SERVER_BASE_URL}
    ports:
      - 127.0.0.1:${CLIENT_PORT}:80
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    secrets:
      - db-password
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db-password
      - DB_DATABASE=${DB_DATABASE}
      - CORS_ORIGIN=${SERVER_CORS_ORIGIN}
    ports:
      - 127.0.0.1:${SERVER_PORT}:80
secrets:
  db-password:
    environment: DB_PASSWORD
