services:
  client:
    build:
      context: .
      dockerfile: docker/client.Dockerfile
      args:
        - SERVER_BASE_URL=${SERVER_BASE_URL}
        - DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-false}
    ports:
      - 127.0.0.1:${CLIENT_PORT}:8080
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    secrets:
      - db-password
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD_FILE=/run/secrets/db-password
      - DB_DATABASE=${DB_DATABASE}
      - CORS_ORIGIN=${SERVER_CORS_ORIGIN}
      - DISABLE_REGISTRATION=${DISABLE_REGISTRATION:-false}
    ports:
      - 127.0.0.1:${SERVER_PORT}:80
    depends_on:
      db-migration:
        condition: service_completed_successfully
  db-migration:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
      target: builder
    command: npx -w chess-server kysely migrate:latest
    secrets:
      - db-password
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD_FILE=/run/secrets/db-password
secrets:
  db-password:
    environment: DB_PASSWORD
